#!/bin/bash
set -e
[ -d 'community-patches' ] && rm -rf 'community-patches'
basedir="$PWD"
wine_tkg_bare="$basedir/bare/wine-tkg-git-bare"
wine_tkg_src="$basedir/wine-tkg-git"
git clone --mirror https://github.com/Frogging-Family/wine-tkg-git "$wine_tkg_bare" || true
cd "$wine_tkg_bare"
git fetch --all -p
git clone "$wine_tkg_bare" "$wine_tkg_src" || true
cd "$wine_tkg_src"
git checkout .
git clean -fd
git pull