#!/bin/bash
git clone https://github.com/Frogging-Family/wine-tkg-git
cd wine-tkg-git/proton-tkg
mkdir -p ~/.config/frogminer
cp /usr/share/wine-docker-builder/configs/proton-tkg-std.cfg ~/.config/frogminer/proton-tkg.cfg
sed -i 's/read -rp "Your S.*/_no_steampath=y/' proton-tkg.sh
sed -i '\+git clone https://github.com/Frogging-Family/community-patches.git$+ s+$+ \&\& cp /usr/share/wine-docker-builder/patches/* community-patches/wine-tkg-git/+' ../wine-tkg-git/wine-tkg-scripts/prepare.sh
./proton-tkg.sh
rm ~/.config/frogminer/proton-tkg.cfg
protonname=`ls -t1 |  head -n 1`
tar -cvf $protonname.tar $protonname
publish-host $protonname.tar