#!/bin/bash
set -e
fetch-wine-tkg
cd wine-tkg-git/wine-tkg-git
sed '\+git clone https://github.com/Frogging-Family/community-patches.git+ s+$+ && cp /usr/share/wine-docker-builder/patches/* wine-tkg-git/+' wine-tkg-scripts/prepare.sh
mkdir -p ~/.config/frogminer
cp wine-tkg-profiles/chaotic-staging.cfg ~/.config/frogminer/wine-tkg.cfg
./non-makepkg-build.sh
rm ~/.config/frogminer/wine-tkg.cfg
cd non-makepkg-builds
winename=`ls -t1 |  head -n 1`
tar -cavf $winename.tar.xz $winename
publish-host $winename.tar.xz