from proton
RUN (apt-get update||true) && apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-base1.0-dev:i386
RUN apt-get install -y fontforge
RUN apt-get install -y fonttools